name: ar_book
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  equatable: ^2.0.0
  http: ^0.13.1
  carousel_slider: 4.0.0
  flutter_svg: ^0.21.0+1
  flutter_launcher_icons: ^0.9.0
  #flutter_html : ^2.2.1
  webview_flutter: ^3.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  flutter_switch: ^0.3.2
  percent_indicator: 3.4.0
  audioplayers: ^0.20.1
  video_player: ^2.2.2
  chewie: ^1.2.0
  url_launcher: ^6.0.6
  # flutter_unity_widget: 2020.3.25
  flutter_i18n: 0.32.3
  shared_preferences: ^2.0.7
  flutter_android: ^0.8.0
  # permission_handler: ^8.1.6
  dio: ^4.0.6
  model_viewer_plus: ^1.2.0
  flutter_secure_storage: ^5.0.2
  fluttertoast: 8.0.7
  flutter_spinkit: 5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  focus_detector: ^2.0.1
  logger: ^1.1.0
  flutter_html: any
  just_audio: ^0.9.31
  audio_service: ^0.18.9
  flutter_file_downloader: ^1.1.2
  path_provider: ^2.0.8
  archive: ^3.3.7
  flutter_archive: ^4.2.0

  #state
  flutter_riverpod: 1.0.0
  state_notifier: ^0.7.2+1

  shimmer: ^2.0.0

  freezed_annotation: 0.14.3

  lottie: ^1.1.0
  animations: ^2.0.2
  wakelock: ^0.6.2
  #checkInternet
  connectivity_plus: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
 
  freezed: 0.14.2

  # Internationalization
  intl_utils: 2.4.0
  json_serializable: 4.1.4

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/i18n/
    - assets/icons/
    - assets/images/
    - assets/images/banner/
    - assets/images/recent/
    - assets/images/category/
#    - assets/logo.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Nunito
       fonts:
         - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
         - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
           weight: 700
     - family: Thai
       fonts:
         - asset: assets/fonts/thai.ttf
     - family: Khmer
       fonts:
         - asset: assets/fonts/khmer.ttf
     - family: Cham
       fonts:
         - asset: assets/fonts/cham.ttf
     - family: TayNguyen
       fonts:
         - asset: assets/fonts/TayNguyenUnicode05.ttf
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios : true
  image_path: "assets/images/conen.png"